<?php
$z[0]=Array("global","",338,367);
$z[0][4]['name']="cfg_templeturl";
$z[1]=Array("global","",432,461);
$z[1][4]['name']="cfg_templeturl";
$z[2]=Array("global","",521,550);
$z[2][4]['name']="cfg_templeturl";
$z[3]=Array("global","",631,660);
$z[3][4]['name']="cfg_templeturl";
$z[4]=Array("global","",733,762);
$z[4][4]['name']="cfg_templeturl";
$z[5]=Array("global","",814,843);
$z[5][4]['name']="cfg_templeturl";
$z[6]=Array("global","",947,976);
$z[6][4]['name']="cfg_templeturl";

?>