<?php
$z[0]=Array("global","",356,385);
$z[0][4]['name']="cfg_templeturl";
$z[1]=Array("global","",450,479);
$z[1][4]['name']="cfg_templeturl";
$z[2]=Array("global","",564,593);
$z[2][4]['name']="cfg_templeturl";
$z[3]=Array("global","",666,695);
$z[3][4]['name']="cfg_templeturl";
$z[4]=Array("global","",744,773);
$z[4][4]['name']="cfg_templeturl";
$z[5]=Array("global","",897,926);
$z[5][4]['name']="cfg_templeturl";

?>